"""运行模式与状态码。

TRACE_MODE:
    test        测试模式：允许降级，但必须显式标记
    offline     离线/演示模式：允许降级，但必须显式标记
    production  生产模式：禁止伪成功
        - 没有 LLM Key 不得生成伪 AI 分析
        - 没有 Telegram Token 不得宣称投递成功
        - 数据源失败不得用 fixture 冒充实时数据
        - 没有行情不得生成虚构市场确认
        - 降级必须显式标记（analysis_mode / market_data_mode）
"""

from __future__ import annotations

import os

# ---- 状态码 ----
STATUS_OK = "OK"
DEGRADED_NO_LLM = "DEGRADED_NO_LLM"
DEGRADED_NO_MARKET_DATA = "DEGRADED_NO_MARKET_DATA"
DEGRADED_NO_EMBEDDER = "DEGRADED_NO_EMBEDDER"
STOP_TELEGRAM_CREDENTIALS_MISSING = "STOP_TELEGRAM_CREDENTIALS_MISSING"
STOP_LLM_KEY_MISSING = "STOP_LLM_KEY_MISSING"
# 默认 Provider（Gemini）缺少 API Key 时的明确停止码（任务书：不得因缺
# OPENAI_API_KEY 停止；缺 GEMINI_API_KEY 时返回此状态）
STOP_TRACE_MVP_V1_GEMINI_KEY_MISSING = "STOP_TRACE_MVP_V1_GEMINI_KEY_MISSING"
STOP_SOURCE_UNAVAILABLE = "STOP_SOURCE_UNAVAILABLE"
# 当日 LLM 调用预算用尽：停止本轮，不得继续消耗配额，也不得静默降级成
# rule_based_degraded 伪装完整分析（区别于缺 Key 的 STOP_*_KEY_MISSING）
STOP_LLM_BUDGET_EXCEEDED = "STOP_LLM_BUDGET_EXCEEDED"
STOP_TELEGRAM_DELIVERY_FAILED = "STOP_TELEGRAM_DELIVERY_FAILED"

# ---- MVP V1 真实验收专用停止码 ----
STOP_TRACE_MVP_V1_TELEGRAM_TOKEN_MISSING = "STOP_TRACE_MVP_V1_TELEGRAM_TOKEN_MISSING"
STOP_TRACE_MVP_V1_TELEGRAM_CHAT_ID_MISSING = "STOP_TRACE_MVP_V1_TELEGRAM_CHAT_ID_MISSING"
STOP_TRACE_MVP_V1_REAL_DELIVERY_FAILED = "STOP_TRACE_MVP_V1_REAL_DELIVERY_FAILED"
STOP_TRACE_MVP_V1_DEEPSEEK_ANALYSIS_FAILED = "STOP_TRACE_MVP_V1_DEEPSEEK_ANALYSIS_FAILED"
STOP_TRACE_MVP_V1_DEEPSEEK_SCHEMA_FAILED = "STOP_TRACE_MVP_V1_DEEPSEEK_SCHEMA_FAILED"
STOP_TRACE_MVP_V1_EVIDENCE_GROUNDING_FAILED = "STOP_TRACE_MVP_V1_EVIDENCE_GROUNDING_FAILED"
STOP_TRACE_MVP_V1_DUPLICATE_ALERT = "STOP_TRACE_MVP_V1_DUPLICATE_ALERT"
STOP_TRACE_MVP_V1_ACCEPTANCE_REPLAY_INVALID = "STOP_TRACE_MVP_V1_ACCEPTANCE_REPLAY_INVALID"

# ---- Source Completion Gate V1 状态码 ----
READY_TRACE_SOURCE_COMPLETION_GATE_V1 = "READY_TRACE_SOURCE_COMPLETION_GATE_V1"
STOP_TRACE_SANDISK_IR_UNAVAILABLE = "STOP_TRACE_SANDISK_IR_UNAVAILABLE"
STOP_TRACE_MICRON_IR_UNAVAILABLE = "STOP_TRACE_MICRON_IR_UNAVAILABLE"
STOP_TRACE_MICRON_IR_RATE_LIMITED_NO_FALLBACK = "STOP_TRACE_MICRON_IR_RATE_LIMITED_NO_FALLBACK"
STOP_TRACE_US_POLICY_SOURCE_UNAVAILABLE = "STOP_TRACE_US_POLICY_SOURCE_UNAVAILABLE"
STOP_TRACE_CN_POLICY_SOURCE_UNAVAILABLE = "STOP_TRACE_CN_POLICY_SOURCE_UNAVAILABLE"
STOP_TRACE_SOURCE_DUPLICATION_UNCONTROLLED = "STOP_TRACE_SOURCE_DUPLICATION_UNCONTROLLED"
STOP_TRACE_SOURCE_FILTER_TOO_NOISY = "STOP_TRACE_SOURCE_FILTER_TOO_NOISY"
STOP_TRACE_SOURCE_COMPLETION_TEST_FAILURE = "STOP_TRACE_SOURCE_COMPLETION_TEST_FAILURE"

# ---- 分析/行情模式标记 ----
ANALYSIS_MODE_LLM = "llm"
ANALYSIS_MODE_RULE_DEGRADED = "rule_based_degraded"
MARKET_DATA_MODE_REAL = "real"
MARKET_DATA_MODE_MOCK = "mock"
MARKET_DATA_MODE_NONE = "none"
# production 下行情未真实接入：禁止 Mock，明确标记为未接入
MARKET_DATA_MODE_UNAVAILABLE = "unavailable"


class TraceMode:
    """从环境变量 TRACE_MODE 读取，默认 offline。"""

    @staticmethod
    def current() -> str:
        return os.environ.get("TRACE_MODE", "offline").strip().lower() or "offline"

    @staticmethod
    def is_production() -> bool:
        return TraceMode.current() == "production"

    @staticmethod
    def validate() -> str:
        mode = TraceMode.current()
        if mode not in ("test", "offline", "production"):
            raise ValueError(f"invalid TRACE_MODE: {mode} (expect test|offline|production)")
        return mode
